name: Build & Test Notebooks

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-notebooks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout notebooks repo
        uses: actions/checkout@v4
        with:
          repository: AnonymousCodes911/notebooks
          path: ./notebooks

      - name: Checkout stingray repo
        uses: actions/checkout@v4
        with:
          repository: StingraySoftware/stingray
          path: ./stingray

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install pandoc
          pip install jupyter
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r notebooks/requirements.txt
          pip install sphinx sphinx-astropy nbsphinx
      - name: Convert Notebooks to RST
        run: |
          find ./notebooks -name "*.ipynb" -exec jupyter nbconvert --to rst {} \;

      - name: Install tox
        run: |
          pip install tox

      - name: Run notebook tests
        run: |
          tox -e notebook_test
          working-directory: ./notebooks

      - name: Build documentation
        run: sphinx-build -b html -d _build/doctrees . _build/html
