name: Build & Test Notebooks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-notebooks:
    runs-on: ubuntu-latest
    steps:
      - name: Print Head Ref
        run: echo "Head Ref: ${{ github.head_ref }}"
      - name: Checkout stingray repo
        uses: actions/checkout@v4
        with:
          repository: StingraySoftware/stingray
          path: ./stingray

      - name: Checkout notebooks repo
        uses: actions/checkout@v4
        with:
          repository: StingraySoftware/notebooks
          ref: ${{ github.head_ref }} 
          path: ./notebooks

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install pandoc and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc fonts-freefont-ttf
          pip install sphinx sphinx-astropy nbsphinx tox

      - name: Update submodules
        run: |
          git submodule update --init --recursive
        working-directory: ./notebooks

      - name: Checkout notebooks submodule branch
        run: |
          git checkout tox-update
        working-directory: ./notebooks

      - name: Run Stingray tox test
        run: |
          tox -e build_docs
        working-directory: ./notebooks
