name: Build & Test Notebooks

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-notebooks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout notebooks repo
        uses: actions/checkout@v4
        with:
          repository: AnonymousCodes911/notebooks
          path: ./notebooks

      - name: Checkout stingray repo
        uses: actions/checkout@v4
        with:
          repository: StingraySoftware/stingray
          path: ./stingray

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install pandoc
          pip install jupyter

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r notebooks/requirements.txt
          pip install sphinx sphinx-astropy nbsphinx

      - name: Convert Notebooks to RST
        run: |
          find ./notebooks -name "*.ipynb" -exec jupyter nbconvert --to rst {} \;

      - name: Install stingray
        run: |
          cd stingray
          pip install .

      - name: Build Docs
        run: |
          tox -e build_docs
