name: Build & Test Notebooks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - tox_update
  workflow_dispatch:

jobs:
  build-notebooks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout stingray repo
        uses: actions/checkout@v4
        with:
          repository: StingraySoftware/stingray
          path: ./stingray

      # checkout the exact version of notebooks submodule
      - name: Checkout notebooks submodule
        run: |
          cd ./stingray
          git submodule update --init --recursive
          cd notebooks
          git fetch origin refs/pull/{pull_request_number}/head:refs/remotes/origin/pull/{99}
          git checkout {99}
          cd ..

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install pandoc and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc fonts-freefont-ttf
          pip install sphinx sphinx-astropy tox

      - name: Install Stingray
        run: pip install -e ./stingray

      - name: Run Build Docs
        run: |
          cd ./stingray
          tox -e build_docs
