name: Build & Test Notebooks

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-notebooks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout notebooks repo
        uses: actions/checkout@v4
        with:
          repository: AnonymousCodes911/notebooks
          path: ./notebooks

      - name: Checkout stingray repo
        uses: actions/checkout@v4
        with:
          repository: StingraySoftware/stingray
          path: ./stingray

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install pandoc
          pip install -r notebooks/requirements.txt
          pip install sphinx sphinx-astropy nbsphinx
          pip install ./stingray  # Install Stingray

      - name: Update the notebooks submodule
        run: | 
          git submodule update --remote --merge

      - name: Run Stingray tox test
        run: |
          tox -e build_docs
        working-directory: ./notebooks
