name: Build & Test Notebooks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-notebooks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout stingray repo
        uses: actions/checkout@v4
        with:
          repository: AnonymousCodes911/stingray
          path: ./stingray

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install pandoc
          pip install sphinx sphinx-astropy nbsphinx

      - name: Install Stingray
        run: pip install ./stingray

      - name: Run Stingray tox test
        run: |
          tox -e build_docs
        working-directory: ./stingray
