name: Build & Test Notebooks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-notebooks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout stingray repo
        uses: actions/checkout@v4
        with:
          repository: StingraySoftware/stingray
          path: ./stingray
          submodules: recursive

      - name: Get latest commit of the PR
        id: pr_commit
        run: |
          PR_SHA=$(curl -s "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}" | jq -r .head.sha)
          if [ "$PR_SHA" == "null" ]; then
            echo "::error::Failed to get PR SHA"
            exit 1
          fi
          echo "::set-output name=commit::$PR_SHA"
      - name: Checkout PR version of notebooks
        run: |
          cd ./stingray/docs/notebooks # Change to the submodule directory
          pwd
          git fetch origin ${{ steps.pr_commit.outputs.commit }}:pr_temp
          git checkout pr_temp
      - name: Verify submodule update
        run: |
          cd ./stingray/docs/notebooks
          git log -1
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install pandoc and additional dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc fonts-freefont-ttf
          pip install sphinx sphinx-astropy tox
          
      - name: Install Stingray
        run: |
          pip install -e ./stingray
      - name: Run Build Docs
        run: |
          cd ./stingray
          tox -e build_docs