name: Build & Test Notebooks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - tox_update
  workflow_dispatch:

jobs:
  build-notebooks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout stingray repo
        uses: actions/checkout@v4
        with:
          repository: StingraySoftware/stingray
          path: ./stingray

      - name: Checkout notebooks repo
        uses: actions/checkout@v4
        with:
          repository: AnonymousCodes911/notebooks
          ref: tox_update
          path: ./notebooks


      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install pandoc and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc fonts-freefont-ttf
          pip install sphinx sphinx-astropy tox

      - name: Install Stingray
        run: pip install -e ./stingray

      - name: Update submodules
        run: |
          cd ./stingray
      #PR version check for PR-99   
      - name: Checkout PR version of notebooks
        run: |
          cd ./notebooks
          git fetch origin pull/${{ github.event.pull_request.number }}/head
          git checkout FETCH_HEAD

      - name: Run Build Docs
        run: |
          cd ./stingray
          tox -e build_docs
