name: Build & Test Notebooks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-notebooks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout stingray repo
        uses: actions/checkout@v4
        with:
          repository: StingraySoftware/stingray
          path: ./stingray

      - name: Checkout notebooks repo
        uses: actions/checkout@v4
        with:
          repository: StingraySoftware/notebooks
          ref: ${{ github.head_ref }}
          path: ./notebooks

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install pandoc
        run: |
          wget https://github.com/jgm/pandoc/releases/download/2.14.2/pandoc-2.14.2-1-amd64.deb
          sudo dpkg -i pandoc-2.14.2-1-amd64.deb

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install pandoc
          sudo apt-get install -y fonts-freefont-ttf
          pip install sphinx sphinx-astropy nbsphinx
      
      - name: Installing Stingray 
        run: |
          pip install -e git+https://github.com/StingraySoftware/stingray.git#egg=stingray

      - name: Update submodules and checkout notebooks submodule
        run: |
          git submodule update --init --recursive
          git checkout main
        working-directory: ./notebooks

      - name: Install Tox
        run: |
          pip install tox

      - name: Run Stingray tox test
        run: |
          tox -e build_docs
        working-directory: ./stingray
