name: Build & Test Notebooks

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-notebooks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install pandoc
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements
      - name: Tox Test
        run: |
          tox -e notebook_test
      