name: Build & Test Notebooks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-notebooks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout stingray repo
        uses: actions/checkout@v4
        with:
          repository: StingraySoftware/stingray
          path: ./stingray
          submodules: true
      - name: Get the latest commit of the PR
        id: pr_commit
        run: |
          PR_SHA=$(curl -s "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}" | jq -r .head.sha)
          if [ -z "$PR_SHA" ]; then
            echo "::error::Failed to retrieve commit hash of the PR"
            exit 1
          fi
          echo "::set-output name=commit::$PR_SHA"

      - name: Checkout PR version of notebooks
        run: |
          PR_SHA=${{ steps.pr_commit.outputs.commit }}
          if [ -z "$PR_SHA" ]; then
            echo "::error::Commit hash is null"
            exit 1
          fi
          cd ./stingray/docs/notebooks  # Change to the submodule directory
          git fetch origin $PR_SHA:pr_temp
          git checkout pr_temp

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install pandoc and additional dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc fonts-freefont-ttf

      - name: Install Stingray
        run: |
          pip install -e ./stingray
      name: Build & Test Notebooks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-notebooks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout stingray repo
        uses: actions/checkout@v4
        with:
          repository: StingraySoftware/stingray
          path: ./stingray
          submodules: recursive

      - name: Get latest commit of the PR
        id: pr_commit
        run: |
          PR_SHA=$(curl -s "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}" | jq -r .head.sha)
          if [ -z "$PR_SHA" ]; then
            echo "::error::Failed to retrieve commit hash of the PR"
            exit 1
          fi
          echo "::set-output name=commit::$PR_SHA"

      - name: Checkout PR version of notebooks
        run: |
          PR_SHA=${{ steps.pr_commit.outputs.commit }}
          if [ -z "$PR_SHA" ]; then
            echo "::error::Commit hash is null"
            exit 1
          fi
          cd ./stingray/docs/notebooks  # Change to the submodule directory
          pwd
          git fetch origin $PR_SHA:pr_temp
          git checkout pr_temp

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install pandoc and additional dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc fonts-freefont-ttf
          pip install sphinx sphinx-astropy tox

      - name: Install Stingray
        run: |
          pip install -e ./stingray

      - name: Run Build Docs
        run: |
          cd ./stingray
          tox -e build_docs
          
      - name: Run Build Docs
        run: |
          cd ./stingray
          tox -e build_docs
