name: Build & Test Notebooks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-notebooks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout stingray repo
        uses: actions/checkout@v4
        with:
          repository: StingraySoftware/stingray
          path: ./stingray
          submodules: recursive

      - name: Print current directory
        run: |
          pwd
          ls ./stingray  # List contents of the stingray directory for reference

      - name: Get latest commit of the PR
        id: pr_commit
        run: |
          echo "::set-output name=commit::$(curl -s "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}" | jq -r .head.sha)"

      - name: Checkout PR version of notebooks
        run: |
          pwd 
          cd ./stingray/docs/notebooks   # Change to the submodule directory
          pwd  # Print current directory for debugging
          git fetch origin ${GITHUB_SHA}:pr_temp
          git checkout pr_temp

      - name: Print updated commit hash
        run: |
          echo "Updated commit hash: ${{ steps.pr_commit.outputs.commit }}"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install pandoc and additional dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc fonts-freefont-ttf

      - name: Install Stingray
        run: |
          pip install -e ./stingray

      - name: Run Build Docs
        run: |
          cd ./stingray
          tox -e build_docs
