name: Build & Test Notebooks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-notebooks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout stingray repo
        uses: actions/checkout@v4
        with:
          repository: StingraySoftware/stingray
          path: ./stingray
          submodules: recursive

      - name: Checkout PR version of notebooks
        run: |
          cd ./stingray/docs/notebooks # Change to the submodule directory
          pwd
          git fetch origin ${{ steps.pr_commit.outputs.commit }}:pr_temp
          git checkout pr_temp
      - name: Verify submodule update
        run: |
          git log -1

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install pandoc and additional dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc fonts-freefont-ttf
          pip install sphinx sphinx-astropy tox
          
      - name: Install Stingray
        run: |
          pip install -e ./stingray

      - name: Run Build Docs
        run: |
          cd ./stingray
          tox -e build_docs
